develop:
  extends:
    file: base.yml
    service: base
  container_name: microservice-node-skeleton
  environment:
    NODE_ENV: dev
    API_GATEWAY_URL: http://192.168.99.100:8000
  command: develop
  volumes:
    - ./app:/opt/microservice-node-skeleton/app
