prod:
  image: vizzuality/gfw-geostore-api:1.0.0${STAGING}
  ports:
    - "3100"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "gelf"
  log_opt:
    gelf-address: ${GELF_ADDRESS}
